# Generated by Django 5.0.3 on 2024-04-01 00:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 1, 0, 3, 13, 578837), verbose_name='date published'),
        ),
    ]
